apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.secret.datasourcePassword | quote }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.backend.secret.redisPassword | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.backend.secret.rabbitmqUsername | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.backend.secret.rabbitmqPassword | quote }}
  SPRING_RABBITMQ_VIRTUAL_HOST: {{ .Values.backend.secret.rabbitmqVhost | quote }}
  SA_TOKEN_JWT_SECRET_KEY: {{ .Values.backend.secret.jwtSecretKey | quote }}
