apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ ternary "NodePort" "ClusterIP" .Values.backend.service.nodePortEnabled }}
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      {{- if .Values.backend.service.nodePortEnabled }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
