apiVersion: v1
kind: Service
metadata:
  name: iot
spec:
  type: ClusterIP
  selector:
    app: iot
  ports:
    - name: http
      port: {{ .Values.iot.service.httpPort }}
      targetPort: http
    - name: netty
      port: {{ .Values.iot.service.nettyPort }}
      targetPort: netty
{{- if .Values.iot.service.nettyNodePortEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: iot-netty-nodeport
spec:
  type: NodePort
  selector:
    app: iot
  ports:
    - name: netty
      port: {{ .Values.iot.service.nettyPort }}
      targetPort: netty
      nodePort: {{ .Values.iot.service.nettyNodePort }}
{{- end }}
