apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: mysql
          image: {{ include "ems-infra.mysqlFullImage" . }}
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
{{ include "ems-infra.timezoneEnv" . | nindent 12 }}
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
{{ include "ems-infra.timezoneVolumeMounts" . | nindent 12 }}
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init-sql
{{ include "ems-infra.timezoneVolumes" . | nindent 8 }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.mysql.storage.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.mysql.storage.size | quote }}
