apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
